spring:
  application.name: cloud-api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password:
    url: jdbc:mariadb://localhost:3306/cloud-db?createDatabaseIfNotExist=true
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: aws.cache.url
    port: 6379
    password:

cloud-api:
  integration:
    service: db

server:
  port: 8080
  servlet.context-path: /api

