
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_manager
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 5000
      idleTimeout: 5000
      maxLifetime: 5000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


logging:
  level:
    org:
      hibernate: ERROR
