

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2000
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
          - java.lang.Exception

  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 2
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
