version: "3.9"  # optional since v1.27.0
services:

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init-script/mariadb:/docker-entrypoint-initdb.d

  keycloak:
    image: jboss/keycloak:15.0.1
    depends_on:
      - mariadb
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: mariadb
      DB_PORT: 3306
      DB_USER: keycloak_user
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: "/tmp/pet-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - ./init-script/keycloak:/tmp

  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: shelter
    volumes:
      - ./init-script/mongoDB/data:/data/db

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 7070:8081

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
    volumes:
      - ./init-script/kafka:/var/run/docker.sock

  schemaregistry:
    image: confluentinc/cp-schema-registry:5.1.2
    restart: always
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
    ports:
      - 8085:8085
