


spring:
  application:
    name: inventory-manager
  cloud:
    function:
      definition: updateStorageConsumer;compensateCreateStorageConsumer;compensateRegisterItemConsumer
    stream:
      rabbit:
        bindings:
          updateStorageConsumer-in-0:
            consumer:
              deadLetterQueueName: compensate.item.register
        default:
          consumer:
            autoBindDlq: true
      bindings:
        CompensateCreateStorageConsumer-in-0:
          destination: compensate.storage.topic
          group: storage
        UpdateStorageConsumer-in-0:
          destination: update.storage.topic
          group: storage

      default:
        contentType: application/json
  rabbitmq:
    broker-url: tcp://127.0.0.1:5672
    username: rabbituser
    password: rabbitpass
    host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_manager?currentSchema=public
    username: postgres
    password: pass
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true