
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bank_broker?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    user: root
    password: password
