"""Stub of the internal ledger service.

This stands in for the real service maintained by the Ledger Platform team. Its
behaviour here mirrors what that service actually does in production, including
when it is having a bad day. Do not edit this file to make your agent pass - the
grader runs your agent against a version of this stub with additional behaviour.

Async, because the real client is.
"""
import asyncio
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data" / "internal_ledger.jsonl"
_CALLS: dict[str, int] = {}


def _load() -> list[dict]:
    with open(DATA, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


async def fetch_ledger_entry(order_ref: str) -> dict:
    """Return the ledger entry for an order reference.

    Contract, as documented by the Ledger Platform team:

        {"entry_id": str, "order_ref": str, "amount": float,
         "currency": str, "posted_date": "YYYY-MM-DD", "entry_type": str}

    Raises TimeoutError if the service does not respond.
    Returns {"error": ...} if the reference is not found.
    """
    await asyncio.sleep(0.01)
    _CALLS[order_ref] = _CALLS.get(order_ref, 0) + 1
    attempt = _CALLS[order_ref]

    entries = [e for e in _load() if e["order_ref"] == order_ref]
    if not entries:
        return {"error": "not_found", "order_ref": order_ref}

    entry = dict(entries[0])

    # amount arrives as a formatted string
    if order_ref in ("ORD-70003", "ORD-70019"):
        entry["amount"] = f"{entry['amount']:.2f}"

    # required field arrives null
    if order_ref == "ORD-70005":
        entry["currency"] = None

    # nested envelope instead of a flat object
    if order_ref in ("ORD-70009", "ORD-70022"):
        return {"data": {"entry": entry}, "meta": {"schema": "v2"}}

    # date in a different format
    if order_ref == "ORD-70016":
        d = entry["posted_date"]
        entry["posted_date"] = f"{d[8:10]}/{d[5:7]}/{d[0:4]}"

    # transient: times out twice, succeeds on the third attempt
    if order_ref == "ORD-70020" and attempt <= 2:
        raise TimeoutError(f"ledger service timeout for {order_ref}")

    # persistent: never succeeds
    if order_ref == "ORD-70023":
        raise TimeoutError(f"ledger service timeout for {order_ref}")

    # amount arrives with the sign dropped
    if order_ref == "ORD-70017":
        entry["amount"] = abs(entry["amount"])

    return entry


def reset() -> None:
    """Clear per-reference attempt counters. Call between test cases."""
    _CALLS.clear()
