spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/stock_db?createDatabaseIfNotExist=true
    username: stock_user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false # To show SQL statement
    properties:
      hibernate:
        format_sql: false # To show SQL statement
        ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master-changelog.json

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
  tracing:
    sampling:
      probability: 1.0

tracing:
  url: http://localhost:4317

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


