
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_broker?currentSchema=public
    username: postgres
    password: pass
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/master_changelog.json
    enabled: true
    drop-first: true
    user: postgres
    password: pass
