services:
  db:
    container_name: postgresDb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
